### PR TITLE
BCN will-thorp

### PR DESCRIPTION
**Pull request by willjthorp**

### CODE REVIEW

**Comment by willjthorp** [comment]
oops, forgot to add <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet"> to the head

**Comment by tawebbcn** [comment]
Are you sure you have linked the proper css file?

**Comment by willjthorp** [comment]
changed it now so it should work!

**Comment by tawebbcn** [comment]
Now works, great job! :1st_place_medal:

**Pull request closed without merging**
